@startuml
class User

class Household
class bi_directional_inverter
class clouds_api
class Heating_controller
class Immersion_water_heater
class Electrical_appliances
class National_Power_Grid
class Batteries
class Renewable_Resources
class Solar_Power
class Solar_Panel
class Wind_Power
class Wind_Turbine


interface Householder_Interface
User -> Householder_Interface
Householder_Interface <|-- bi_directional_inverter

bi_directional_inverter <|-- Renewable_Resources
bi_directional_inverter <|-- Batteries
bi_directional_inverter <|-- National_Power_Grid


Renewable_Resources <|-- Solar_Power
Renewable_Resources <|-- Wind_Power
Solar_Power <|-- Solar_Panel
Wind_Power <|-- Wind_Turbine


@enduml
