@startuml
class User

interface HouseInterface{
+change_Source()
+usage_update()
}
interface PowerSource{
+Power_Generated() : int
}
interface PowerConsumer{
+Power_Usage() : int
}

class CloudApi{
- current_use_watts : int
+ usage_update() : int
+ monthly_report() : void
+ weekly_report() : void
+ daily_report() : void
}

class BiDirectionalInverter{
-current_power_source
-Timer
+cloud_update()
+getstatus() : boolean
}
class NationalPowerGrid{
-grid_energy_generated
+generate_power() : boolean
}

interface RenewableResources{
+generate_power() : boolean
+not_generating() : boolean
}
class HeatingController{
-current_state : boolean
+turn_on() : boolean
+turn_off() : boolean
}

class HouseholdAppliances{
-current_state : boolean
+consumption_per_hour()
+turn_on_appliance() : boolean
+turn_off_appliance() : boolean
}


class Batteries{
-battery_percentage : int
+currentbatterypercentage() : int
+charged()
}


class SolarPower{
-solarpower_generated
+total_solarpower() : int
}

class WindPower{
-windpower_generated
+total_windpower() : int
}
class SolarPanel{
-solar_panel_id
+power_generated():
}
class WindTurbine{
-wind_turbine_id
+power_generated():
}

class ElectricKettle
class ImmersionWaterHeater

User -- HouseInterface
HouseInterface -> CloudApi
HouseInterface <|-- BiDirectionalInverter
CloudApi"1" --- "1"BiDirectionalInverter
BiDirectionalInverter --> PowerSource
BiDirectionalInverter --> PowerConsumer
RenewableResources <|.. SolarPower 
RenewableResources <|.. WindPower 
SolarPower "1" --  "0..*" SolarPanel
WindPower"1" -- "0..*" WindTurbine


PowerSource <|.. RenewableResources
PowerSource <|.. NationalPowerGrid
PowerSource <|.. Batteries
PowerConsumer <|.. HouseholdAppliances
PowerConsumer <|.. Batteries
PowerConsumer <|.. NationalPowerGrid
PowerConsumer <|.. HeatingController
HouseholdAppliances"1" <|.. "Many"ElectricKettle
HeatingController <|.. ImmersionWaterHeater
Batteries ..> ImmersionWaterHeater
@enduml
